import React, { useState, useEffect } from 'react';

function History() {
  const [data, setData] = useState(null);
  const [coupons, setCoupons] = useState(null);
  const currentDate = new Date().toLocaleDateString('pt-PT').split('/').join('.');
  const today = new Date();

  const options = {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      Connection: 'keep-alive',
      'X-RapidAPI-Key': 'e734dbcf78msh009a1346b3596d6p1b5dc3jsn450f7106833f',
      'X-RapidAPI-Host': 'daily-betting-tips.p.rapidapi.com'
    }
  };

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(`https://daily-betting-tips.p.rapidapi.com/daily-betting-tip-api/items/daily_betting_tips?q=${currentDate}&sort=-id`, options);
        const data = await response.json();
        setData(data);
      } catch (error) {
        console.error(error);
      }
    };

    const fetchCoupons = async () => {
      try {
        const response = await fetch(`https://daily-betting-tips.p.rapidapi.com/daily-betting-tip-api/items/daily_betting_coupons?sort=-id`, options);
        const coupons = await response.json();
        setCoupons(coupons);
      } catch (error) {
        console.error(error);
      }
    };


  }, []);

  return (
    <div className="bg-gray-50">
      <header>
        <nav className="bg-white shadow-sm">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 justify-between">
              <div className="flex">
                <div className="flex flex-shrink-0 items-center">
                  <svg width="32" height="32" viewBox="0 0 32 32" fill="none" className="text-gray-100" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" rx="16" fill="currentColor"></rect><path fillRule="evenodd" clipRule="evenodd" d="M17.6482 10.1305L15.8785 7.02583L7.02979 22.5499H10.5278L17.6482 10.1305ZM19.8798 14.0457L18.11 17.1983L19.394 19.4511H16.8453L15.1056 22.5499H24.7272L19.8798 14.0457Z" fill="black"></path></svg>
                </div>
                <div className="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
                  <a href="/" className="border-slate-500 text-gray-800 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" aria-current="page">Today's tips</a>
                  <a href="/history" className="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">History</a>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main className="p-4 md:p-10 mx-auto max-w-7xl">
        <h1 className="text-3xl font-bold text-gray-800">Daily Predictions ({currentDate})</h1>
        <p className="text-sm text-gray-800 mt-4">We provide 75% hit rate daily football and basketball betting predictions.<br/>Our predictions are generated by AI powered analysis of previous matches and other factors key to the game’s result.</p>
        <h2 className="text-2xl font-bold text-gray-800 mt-12">Free tips</h2>
        {data != null ? (
          <div className="relative overflow-x-auto mt-4">
            <table className="w-full text-sm text-left text-gray-800 shadow border border-gray-200 rounded-lg">
              <thead className="text-xs text-gray-800 uppercase bg-gray-50">
                <tr>
                  <th scope="col" className="px-6 py-3">
                    Match
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Match time
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Tip
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Odd
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody>
                {data.data.map(item => (
                  <tr key={item.id} className="bg-white border-b">
                    <th scope="row" className="px-6 py-4 font-medium text-gray-800 whitespace-nowrap">
                      {item.home_team} - {item.away_team} <small>({item.league_name})</small>
                    </th>
                    <td className="px-6 py-4">
                      {item.match_time}
                    </td>
                    <td className="px-6 py-4">
                      {item.game_prediction}
                    </td>
                    <td className="px-6 py-4">
                      {item.odd_value}
                    </td>
                    <td className="px-6 py-4">
                      <button
                      className=
                      {`px-2 py-1 text-white text-xs font-medium rounded-full min-w-[70px] ${
                        item.match_status === 'pending' ? 'bg-yellow-400' :
                        item.match_status === 'won' ? 'bg-green-400' :
                        'bg-red-300'
                      }`}>
                      	{item.match_status}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p>Loading...</p>
        )}
        {coupons != null ? (
          <>
          <h2 className="text-xl font-bold text-gray-800 mt-8">Premium Coupons</h2>
          <div className="mt-4 md:grid md:grid-cols-4 md:gap-4">
            {coupons.data.map(coupon => (
              <div key={coupon.id} className="w-full max-w-md p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8">
                <div className="flex items-center justify-between mb-4">
                  <h5 className="text-lg font-bold leading-none text-gray-800 dark:text-white">{coupon.coupon_name}</h5>
                 </div>
                 <div className="flow-root">
                    <ul role="list" className="divide-y divide-gray-200">
                      {coupon.coupons_list_data.map(bet => (
                        <li key={bet.id} className="py-3 sm:py-4">
                          <div className="flex items-center space-x-4">
                            <div className="flex-1 min-w-0">
                              <p className="text-sm font-medium text-gray-800">
                                <strong>Match:</strong><br/><small>{bet.home_team} - {bet.away_team}</small>
                              </p>
                              <p className="text-sm text-gray-800 mt-2">
                                <strong>Prediction:</strong><br/><small>{bet.game_prediction} ({bet.odd_value})</small>
                              </p>
                              <p className="text-sm text-gray-800 mt-2">
                                <strong>Result:</strong><br/><small>{bet.match_status}</small>
                              </p>
                            </div>
                          </div>
                        </li>
                      ))}
                    </ul>
                 </div>
              </div>
            ))}
          </div>
        </>
        ) : (
          <p>Loading...</p>
        )}
      </main>
    </div>
  );
}

export default History;
