import React, { useState, useEffect } from 'react';

function App() {
  const [data, setData] = useState(null);
  const currentDate = new Date().toLocaleDateString('pt-PT').split('/').join('.');

  useEffect(() => {
    const fetchData = async () => {
      const options = {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          Connection: 'keep-alive',
          'X-RapidAPI-Key': '93a741cfe2mshc8321b2b0670ee3p1845edjsn7a78d9ffbaf8',
          'X-RapidAPI-Host': 'daily-betting-tips.p.rapidapi.com'
        }
      };

      try {
        const response = await fetch(`https://daily-betting-tips.p.rapidapi.com/daily-betting-tip-api/items/daily_betting_tips?q=${currentDate}&sort=-id`, options);
        const data = await response.json();
        setData(data);
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();

  }, []);

  return (
    <div className="bg-gray-50">
      <header>
        <nav className="bg-white shadow-sm">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 justify-between">
              <div className="flex">
                <div className="flex flex-shrink-0 items-center">
                  <svg width="32" height="32" viewBox="0 0 32 32" fill="none" className="text-gray-100" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" rx="16" fill="currentColor"></rect><path fillRule="evenodd" clipRule="evenodd" d="M17.6482 10.1305L15.8785 7.02583L7.02979 22.5499H10.5278L17.6482 10.1305ZM19.8798 14.0457L18.11 17.1983L19.394 19.4511H16.8453L15.1056 22.5499H24.7272L19.8798 14.0457Z" fill="black"></path></svg>
                </div>
                <div className="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
                  <a href="/" className="border-slate-500 text-gray-800 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" aria-current="page">Today tips</a>
                  <a href="/stats" className="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">Stats</a>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main className="p-4 md:p-10 mx-auto max-w-7xl">
        <h2 className="text-2xl font-bold leading-7 text-gray-800 sm:truncate sm:text-3xl sm:tracking-tight">Today predictions - {currentDate}</h2>
        <p className="text-sm text-gray-800 mt-4">We provide 90% hit rate daily soccer and basketball betting predictions, Our predictions are generated by AI powered analysis of previous matches and other factors key to the game’s result</p>
        {data ? (
          <div className="relative overflow-x-auto mt-8">
            <table className="w-full text-sm text-left text-gray-800 dark:text-gray-400">
              <thead className="text-xs text-gray-800 uppercase bg-gray-50">
                <tr>
                  <th scope="col" className="px-6 py-3">
                    Match
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Match time
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Tip
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Odd
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody>
                {data.data.map(item => (
                  <tr key={item.id} className="bg-white border-b">
                    <th scope="row" className="px-6 py-4 font-medium text-gray-800 whitespace-nowrap">
                      {item.home_team} - {item.away_team} <small>({item.league_name})</small>
                    </th>
                    <td className="px-6 py-4">
                      {item.match_time}
                    </td>
                    <td className="px-6 py-4">
                      {item.game_prediction}
                    </td>
                    <td className="px-6 py-4">
                      {item.odd_value}
                    </td>
                    <td className="px-6 py-4">
                      {item.match_status}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p>Loading...</p>
        )}
      </main>
    </div>
  );
}

export default App;
